=== FLXForge/FLXEngine/tools/schemas/main.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "title": "FLX Main",

  "type": "object",

  "properties": {

    "name": {
      "type": "string"
    },

    "description": {
      "type": "string"
    },

    "screen": {

      "type": "object",

      "properties": {

        "title": {
          "type": "string"
        },

        "width": {
          "type": "integer"
        },

        "height": {
          "type": "integer"
        }

      }

    },

    "scale": {
      "type": "integer"
    },

    "program": {
      "type": "object",
      "properties": {
        "scripts": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [ "scripts" ],
      "additionalProperties": false
    },

    "children": {

      "type": "array",

      "items": {

        "oneOf": [
          { "type": "string" },
          { "$ref": "node.schema.json" }
        ]

      }

    },

    "spawns": {
      "$ref": "spawns.schema.json"
    }

  },

  "required": [
    "name",
    "screen",
    "children"
  ]
}

=== FLXForge/FLXEngine/examples/asteroids/game.json
{
  "$schema": "../../tools/schemas/game.schema.json",
  "name": "Asteroids",
  "description": "Example of more famous game",

  "screen": {
    "title": "Asteroids",
    "width": 640,
    "height": 320
  },
  "scale": 3,

  "children": ["levels/level"],

  "program": {
    "scripts": [ "scripts/program" ]
  }
}
